workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      groups:
        - development
      vars:
        XCODE_WORKSPACE: "ios/meetgo.xcworkspace"
        XCODE_SCHEME: "meetgo"
        IPHONEOS_DEPLOYMENT_TARGET: "15.5"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "BD46Y2FML8"
        APP_STORE_CONNECT_ISSUER_ID: "c76b0f32-e565-4479-90c9-edc2487340a7"
        BUNDLE_ID: "app.meetgo.vn"
        TEAM_ID: "M73GARWH95"
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    scripts:
      - name: Install dependencies
        script: |
          npm install && npx patch-package
          cd ios && pod install && cd ..
          
      - name: Set up code signing
        script: |
          # Fetch signing files
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          
          # Set up code signing settings
          xcode-project use-profiles --warn-only
          
      - name: Update Pod targets and Swift optimization
        script: |
          cd ios
          # Update deployment targets to 15.5 
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' Pods/Target\ Support\ Files/*/*.xcconfig || true
          
          # Fix Swift optimization level for debugging
          find Pods/Target\ Support\ Files -name "*.xcconfig" -exec sed -i '' 's/SWIFT_OPTIMIZATION_LEVEL = -Owholemodule;/SWIFT_OPTIMIZATION_LEVEL = -Onone;/g' {} \;
          find Pods/Target\ Support\ Files -name "*.xcconfig" -exec sed -i '' 's/SWIFT_OPTIMIZATION_LEVEL = -O;/SWIFT_OPTIMIZATION_LEVEL = -Onone;/g' {} \;
          
          # Update main project settings
          find . -name "*.xcconfig" -exec sed -i '' 's/SWIFT_OPTIMIZATION_LEVEL = -O[a-z]*;/SWIFT_OPTIMIZATION_LEVEL = -Onone;/g' {} \;
          cd ..
          
      - name: Generate exportOptions.plist
        script: |
          cat > ios/exportOptions.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOL
          
      - name: Build iOS app
        script: |
          mkdir -p build
          set -x
          
          echo "Starting build process with team ID: $TEAM_ID"
          
          # Clean build
          xcodebuild clean \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -configuration Release
          
          # Build archive
          xcodebuild \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/meetgo.xcarchive \
          IPHONEOS_DEPLOYMENT_TARGET=15.5 \
          DEVELOPMENT_TEAM="$TEAM_ID" \
          CODE_SIGN_STYLE="Automatic" \
          SWIFT_OPTIMIZATION_LEVEL="-Onone" \
          -allowProvisioningUpdates \
          archive | tee xcodebuild.log
          
          # Check if archive was created
          if [ -d "build/meetgo.xcarchive" ]; then
            echo "Archive created successfully"
            xcodebuild \
            -exportArchive \
            -archivePath build/meetgo.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ios \
            -allowProvisioningUpdates
          else
            echo "Archive creation failed"
            tail -n 100 xcodebuild.log
            exit 1
          fi
    artifacts:
      - build/ios/*.ipa
      - xcodebuild.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true